import type { Metadata } from "next";

import { Oswald } from "next/font/google";
import "./globals.css";
import NavbarPage from "@/components/Navbar";
import FooterPage from "@/components/FooterPage";
import FitLogProvider from "@/context/FitLogContext";

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "B-14-A6-FIT-LOG-BY-SHAHARIAR",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${oswald.variable}`}>
      <body className="min-h-full flex flex-col">

      <FitLogProvider>

        <NavbarPage />

        <main>{children}</main>

        <FooterPage />
      </FitLogProvider>
      </body>
    </html>
  );
}
